TaiBIF/camera-trap-webapp

.eslintrc.js
package-lock.json
package.json
prettier.config.js

After this PR is merged.
Use `npm run lint` to fix all

ESLint + Vue + pre-commit hooks

---

src/components/Header/TheHeader.vue
src/pages/article/App.vue
src/pages/history/App.vue
src/pages/index/App.vue
src/pages/intro/App.vue
src/pages/login/App.vue
src/pages/search/App.vue
src/pages/setting/App.vue
src/pages/upload/App.vue

* 先建立登入/未登入兩個版本, 後續再處理 active link 部分
* intro
* login
* index
* article
* history
* search
* setting
* upload

create header component

---

src/components/Header/TheHeader.vue
src/sass/globals/_global.sass
src/service/api.js
src/service/modules/notification.js
src/service/modules/user.js
src/stores/modules/auth.js
src/stores/modules/message.js
src/util/auth/cognito-config.js
src/util/fetch.js

* 依照 route name 顯示 active link
* bind signOut click event (doSignOut action 目前無法 work 待確認)
* 串接 API load user profile (API response 5xx, 待確認)
* 串接 API load notifications (API response 5xx, 待確認)
* 修正 sign-in base url
* header style 微調, 增加 幫助btn hover & notification 紅點

header 相關功能

---

.env.development
.env.development.local
.env.production
.env.test
.gitignore
package.json
src/util/auth/cognito-config.js
src/util/fetch.js

local / development / test / production

set env file

---

src/pages/index/views/Site.vue
src/stores/modules/media.js

feat: 實作加入新的 data

---

src/pages/index/components/EditNav.vue
src/pages/index/views/CreateProject.vue
src/pages/index/views/EditInfo.vue
src/pages/index/views/Project.vue
src/service/modules/project.js
src/stores/modules/project.js

將部分頁面 route 由 projectTitle 修正為 project._id,
vuex currentProject 也同步改用 project._id 對應

apply project._id

---

src/pages/index/components/SiteChart.vue
src/pages/index/views/Project.vue

#16 
> 依照確認邏輯繪製 影像回收/辨識狀況 chart
> 修正 setSiteMarker 邏輯
PS.
1. 目前 Project.vue 中 fetchImageStatus 的處理方式會有問題, 暫時用setTimeout處理, 已備註 TODO 後續應花時間重新設計此頁面資料流
2. 目前切換樣區時數量統計有誤, 會接續處理這部分

adjust retrived, identied chart

---

src/pages/index/views/Overview.vue

modified earliest record year on project card of overview

---

src/service/modules/media.js
src/service/modules/project.js
src/stores/modules/media.js

修正部分 projectTitle => projectId 造成的前端顯示錯誤

fix some projectTitle => projectId bugs

---

src/pages/index/views/Project.vue

#17
1. 計算 adnormal status
2. 顯示異常於 barchart

點擊月份長條顯示是否有異常情況

---

src/mixins/common.js
src/pages/index/views/EditInfo.vue
src/service/modules/project.js
src/util/uploadToS3.js

#51 
upload cover image to S3 and save the URL to project.coverImage

upload cover image

---

src/util/uploadToS3.js

改寫了 S3 ManagedUpload 的參數寫法，加入 messages:[] 到 upload-session 的編輯樣板。

modify upload related function call and req property

---

src/pages/index/views/EditColumn.vue
src/util/roles.js

https://github.com/TaiBIF/camera-trap-webapp/issues/52
3.2.1 檢查登入人員權限，若為「計畫管理員」則顯示「+新增欄位」
(also add some missing data/component within this PR)

display add column btn base on user role 

---

src/pages/index/views/CreateProject.vue
src/sass/elements/_form.sass
src/service/modules/project.js

close #13 
* 修正 api 參數, 改用 projectId
* 處理必填欄位檢查
* 處理欄位預設
* 上傳封面功能

Feature 13 新增計畫

---

src/pages/index/components/SiteItem.vue
src/pages/index/views/EditCamera.vue
src/service/modules/project.js
src/stores/index.js
src/stores/modules/project.js

#62 相機位置管理: 3.4 列出計畫下的相機位置與資訊
* load project
* display site & subsite
* display camera table (API 缺架設日期暫不顯示)

load project and display camera

---

src/pages/history/views/History.vue
src/pages/index/views/Site.vue
src/stores/modules/cameraLocation.js

#108 
#66 
#99 
目前有幾個問題，修正後在 merge
#66 缺少 project id 跟 fullCameraLocationMd5 目前寫死，需修改以下連結程式
https://github.com/TaiBIF/camera-trap-webapp/commit/66ab30fc42d8fe8454b64425b4c24df2a360d33f#diff-4da499156aa500419dc89d864c2d925cR85
#99 已經不會創建多個了，不過在模式切換時有時候底下的高度並沒有跟著變大或變小

Feature fix misc

---

src/pages/index/components/SiteItem.vue
src/pages/index/components/SiteMenu.vue
src/pages/index/views/EditCamera.vue
src/service/modules/project.js
src/stores/index.js
src/stores/modules/project.js

#62 
rename site, subSite
* double click 進入編輯狀態
* enter or blur 離開編輯並保留編輯結果
* esc 離開編輯並回復編輯前資訊
* 點擊儲存call api update資料

rename site, subSite

---

src/pages/index/views/CreateProject.vue
src/pages/index/views/Project.vue
src/pages/login/views/Login.vue
src/service/api.js
src/service/modules/exampleFiles.js
src/service/modules/project.js
src/stores/index.js
src/stores/modules/exampleFiles.js
src/util/fetch.js

Feature misc 3

---

src/pages/index/components/YoutubeEmbed.vue
src/pages/index/views/Site.vue
src/service/modules/media.js
src/stores/modules/annotationRevision.js
src/stores/modules/media.js

Feature misc 4

---

package.json
src/pages/index/components/SiteMenu.vue
src/pages/index/views/EditCamera.vue
src/util/transfer.js

related #62 
* install proj4 (TWD97 轉 wgs84)
* edit camera data function

edit camera location data

---

src/pages/index/views/EditCamera.vue
src/util/transfer.js

close #62 
* add new camerate location
* error handle for twd97ToWgs84

add new camera location

---

src/pages/index/views/EditCamera.vue
src/sass/globals/_global.sass
src/sass/globals/_page.sass

related: #62 
* if elevation is not number, show error message and disable save button
* fix handsontable first render error

add input validate and error message

---

src/pages/index/views/EditColumn.vue
src/service/modules/project.js
src/stores/modules/project.js

relate #52 
* load additional column from API
* delete column
* sort column

handle column field

---

src/pages/index/components/NewColumn.vue
src/pages/index/views/EditColumn.vue
src/sass/globals/_global.sass
src/stores/modules/project.js

* download CSV
* load and update dailyTestTime
* add new column (from current field)
* adjust new column input

Feature 52

---

src/pages/index/components/DialogUI.vue
src/pages/index/components/NewColumn.vue
src/pages/index/views/EditColumn.vue
src/sass/globals/_global.sass
src/service/modules/project.js

related: #52 
* error handle when user not input option for select type
* apply API: https://github.com/TaiBIF/camera-trap-api/issues/21
* success dialog

Feature 52 - apply new column field

---

src/pages/index/components/EditNav.vue
src/pages/index/router.js
src/pages/index/views/EditColumn.vue
src/pages/index/views/Project.vue
src/util/roles.js

* roles change to role (https://github.com/TaiBIF/camera-trap-webapp/issues/64#issuecomment-446863698)
* permission control for project edit page (https://github.com/TaiBIF/camera-trap-api/wiki/role-permission)

permission for edit page

---

src/pages/index/components/SpeciesOrder.vue
src/pages/index/views/EditColumn.vue
src/stores/modules/project.js

relate: #53 
* load species list
* edit current species
* delete current species
* reorder species
* add new species

edit speciesList order

---

src/pages/setting/views/Setting.vue
src/service/modules/user.js
src/stores/modules/auth.js
src/stores/modules/project.js

relate: #69 
* load username and email
* edit username and email
* load speciesKeys
* get speciesKeys option from all project's speciesList
* edit speciesKeys
* reset speciesKeys

settings profile and hotkey

---

.env.local
src/pages/setting/views/Setting.vue
src/util/intToChar.js

relate: #69 
* hide add hotkey button if all species already been set
* generate default hotkey
* limit hotkey length

generate default hotkey

---

src/pages/index/views/Project.vue

fixed: #16 
adjust render chart logic when switch year

watch location data to renderMap

---

src/pages/index/components/ReportModal.vue
src/pages/index/views/Project.vue

relate: #20 
* add projectId for API response param
* validate required input

adjust update abnormal camera

---

src/pages/index/views/EditLicense.vue
src/service/modules/project.js
src/stores/modules/project.js

load and edit project license

---

src/pages/index/components/TreeItem.vue
src/pages/index/components/TreeMenu.vue
src/pages/index/views/Site.vue
src/stores/modules/project.js

relate: #15 
display treeitem red dot base on abnormal camera information
(TBC: abnormal camera query range https://github.com/TaiBIF/camera-trap-webapp/issues/15#issuecomment-449378318)

sidebar error notice

---

src/pages/index/App.vue
src/pages/index/components/TreeItem.vue
src/pages/index/views/Site.vue
src/sass/components/_tree.sass
src/service/modules/project.js
src/stores/modules/project.js

#15 
show red dot base on site abnormal record
https://github.com/TaiBIF/camera-trap-api/wiki/annotation#%E4%B8%80%E6%AC%A1%E5%8F%96%E5%BE%97%E6%89%80%E6%9C%89%E6%A8%A3%E5%8D%80%E6%98%AF%E5%90%A6%E6%9C%89%E9%8C%AF%E8%AA%A4

get project error sites and apply on treeitem

---

src/pages/index/views/CreateProject.vue
src/pages/index/views/EditInfo.vue
src/pages/index/views/Project.vue
src/pages/upload/views/Upload.vue
src/service/modules/project.js
src/stores/modules/auth.js
src/util/auth/cognito-config.js
src/util/uploadToS3.js

fix missing credentials

---

src/pages/index/views/EditInfo.vue
src/pages/index/views/Overview.vue
src/pages/index/views/Site.vue
src/stores/modules/media.js

- 修正連拍顯示
- 編輯計畫時顯示已上傳的封面照
- 修正禁止編輯的欄位會被 handsontable drag-to-fill 功能強迫寫值的 bug

fix sheet edit mode bugs, fix project cover image display

---

src/pages/index/views/EditLicense.vue
src/service/modules/project.js

#65 
handle load/edit publishDate & input validate

handle edit publishDate

---

src/pages/article/components/SuccessModal.vue
src/pages/article/views/Contact.vue

apply submit success modal

---

src/pages/index/views/MemberDescription.vue
src/sass/elements/_table.sass

https://github.com/TaiBIF/camera-trap-webapp/issues/64#issuecomment-451042231
...

add back button

---

src/pages/index/components/ErrorModal.vue
src/pages/index/components/SiteMenu.vue
src/pages/index/components/SuccessModal.vue
src/pages/index/views/EditCamera.vue
src/sass/globals/_page.sass
src/service/modules/project.js
src/stores/modules/project.js

close #189 
* new site input format adjust
* required column validate
* error modal
* success modal

Feature 189 adjust location management

---

src/pages/index/views/Site.vue
src/service/modules/media.js

revert #167 只保留部分樣式及 Handsontable 部分，將顯示從天數改回筆數

Revert #167
